# Coolify 配置文件
version: '1.0'

services:
  - name: formuless
    type: application
    buildPack: dockerfile
    port: 3000
    
    # 环境变量
    env:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/prod.db
    
    # 持久化存储
    volumes:
      - source: /app/data
        destination: formuless-data
        persistent: true
    
    # 健康检查
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
    
    # 自动重启
    restart: unless-stopped
